update Dockerfile
kbase/feeds pull request #88
Opened 2024-11-20 00:15 UTC by Xiangs18

2024-11-20 01:43 UTC, MrCreosote reviewed
Mostly looks good, just not sure if there's anything in the kb python image that we're missing by switching to a standard python image

2024-11-20 01:43 UTC, MrCreosote commented on Dockerfile
> +RUN ln -s /opt/dockerize /kb/deployment/bin/dockerize
I assume you copied this from the kb_python:python3 dockerfile? There's nothing else in there that needs to be transferred over?

2024-11-20 02:18 UTC, Xiangs18 commented on Dockerfile
> +RUN ln -s /opt/dockerize /kb/deployment/bin/dockerize
I copied from https://github.com/kbase/handle_service2/blob/develop/Dockerfile

2024-11-20 02:47 UTC, MrCreosote commented on Dockerfile
> +RUN ln -s /opt/dockerize /kb/deployment/bin/dockerize
Ok, so it's not clear to me whether there's anything we're missing from the original image then

2024-11-20 04:38 UTC, Xiangs18 commented on Dockerfile
> +RUN ln -s /opt/dockerize /kb/deployment/bin/dockerize
> There's nothing else in there that needs to be transferred over?

No, as far as I know, there's nothing else that needs to be transferred.

2024-11-20 17:38 UTC, MrCreosote commented on Dockerfile
> +RUN ln -s /opt/dockerize /kb/deployment/bin/dockerize
How did you verify that?

2024-11-20 18:36 UTC, Xiangs18 commented on Dockerfile
> +RUN ln -s /opt/dockerize /kb/deployment/bin/dockerize
docker build, run, and curl

2024-11-20 19:10 UTC, MrCreosote commented on Dockerfile
> +RUN ln -s /opt/dockerize /kb/deployment/bin/dockerize
that doesn't mean there's nothing missing, just that the service starts

2024-11-20 20:31 UTC, MrCreosote commented on Dockerfile
> +RUN ln -s /opt/dockerize /kb/deployment/bin/dockerize
Could be lots of things, cron job setups, optional performance libs, os tweaks, binaries that are only used in rare cases and not on startup, etc. We can't just assume that switching from a specialized kbase image to a general image is ok. Maybe it is, but we need to check

2024-11-20 20:56 UTC, Xiangs18 commented on Dockerfile
> +RUN ln -s /opt/dockerize /kb/deployment/bin/dockerize
Why don’t we deploy the image to CI and see if anything strange shows up in the error logs? This way, we can confirm whether the switch is okay or if there’s something important we're missing. Please let me know if there are any specific checks or tests you want me to conduct. Both handle_service2 and IdMappingService have already undergone the switch smoothly. To me, the feeds aren’t that different from them.

2024-11-20 21:18 UTC, MrCreosote commented on Dockerfile
> +RUN ln -s /opt/dockerize /kb/deployment/bin/dockerize
The IDmapping service was just a version bump, not switching from a kbase specific image to a general image. I knew enough about the HS2 service and the sdk base image to know that switching from the sdkpython to a general python image wasn't a problem. I don't know enough about the service or the image to come to that conclusion for this repo.

Just starting up the service and looking at the logs doesn't tell us if a cron job isn't starting or whether we'll have performance issues or failures down the road because of image differences, etc.

2024-11-20 21:41 UTC, Xiangs18 commented on Dockerfile
> +RUN ln -s /opt/dockerize /kb/deployment/bin/dockerize
Okay, now I see where you're coming from. 
Perhaps @briehl could weigh in, as he has more expertise on `feeds` than either of us.

2024-11-20 21:48 UTC, MrCreosote commented on Dockerfile
> +RUN ln -s /opt/dockerize /kb/deployment/bin/dockerize
Why not find the dockerfile for the original base image? That'll tell us exactly what the differences are

2024-11-20 21:56 UTC, briehl reviewed
Added comments.

2024-11-20 21:56 UTC, briehl commented on Dockerfile
> +RUN ln -s /opt/dockerize /kb/deployment/bin/dockerize
Here's the kbase/kb_python:python3 Dockerfile, you can check it for differences.
https://github.com/kbase/kb_python/blob/master/Dockerfile

and the minideb Dockerfile: https://github.com/kbase/kb_minideb/blob/master/Dockerfile
which really just looks like the mini debian image + dockerize.

2024-11-20 21:56 UTC, briehl commented on Dockerfile
> +RUN ln -s /opt/dockerize /kb/deployment/bin/dockerize
While we're at it, is it possible to get a later Python version? 3.9 will be EOL next year, and we'll have to do this whole dance again.

Unless you're sticking with that for this global security update, in which case that's fine. I'm not trying to make more work.

2024-11-20 21:59 UTC, briehl commented on Dockerfile
> +RUN ln -s /opt/dockerize /kb/deployment/bin/dockerize
Also, @bio-boris might want to chime in if there are security issues in the base image. But I guess that's trivy's job to catch. Is the trivy GHA task on this repo?

2024-11-20 22:03 UTC, MrCreosote commented on Dockerfile
> +RUN ln -s /opt/dockerize /kb/deployment/bin/dockerize
Because there's so many services to do and we're trying to finish before EOY, we're sticking to just changes necessary for the Mongo7 upgrade. Once that's done the next step is to make a dashboard of some kind that shows every service, their vulns, upgrades needed, test status, and coverage. Then we'll triage

2024-11-20 22:13 UTC, Xiangs18 commented on Dockerfile
> +RUN ln -s /opt/dockerize /kb/deployment/bin/dockerize
Where is that `dockerize` coming from?https://github.com/kbase/kb_minideb/blob/adbb3b14388157ff0d6b5d963af7b753891db1fa/Dockerfile#L13

2024-11-20 22:14 UTC, MrCreosote commented on Dockerfile
> +RUN ln -s /opt/dockerize /kb/deployment/bin/dockerize
It must be in the base image I presume

2024-11-20 22:24 UTC, MrCreosote commented on Dockerfile
> +RUN ln -s /opt/dockerize /kb/deployment/bin/dockerize
Whatever the image the Dockerfile is based on, yeah

2024-11-20 22:34 UTC, Xiangs18 commented on Dockerfile
> +RUN ln -s /opt/dockerize /kb/deployment/bin/dockerize
Dockerize is installed on the host machine and then copied to the image. It cannot from `bitnami/minideb:stretch`.

2024-11-20 22:48 UTC, MrCreosote commented on Dockerfile
> +RUN ln -s /opt/dockerize /kb/deployment/bin/dockerize
Ah, I misread the docker file. Looks like it's coming from here: https://github.com/kbase/kb_minideb/blob/adbb3b14388157ff0d6b5d963af7b753891db1fa/Makefile#L8-L11

2024-11-20 22:51 UTC, MrCreosote commented
Hm, there's a lot of stuff installed in there and I don't know if any of it is needed. @briehl will have to answer

2024-11-20 22:56 UTC, bio-boris commented on Dockerfile
> +RUN ln -s /opt/dockerize /kb/deployment/bin/dockerize
I'm for using the latest python that passes trivy scans

2024-11-21 21:46 UTC, briehl requested changes
> Hm, there's a lot of stuff installed in there and I don't know if any of it is needed. @briehl will have to answer

It needs dockerize, which is there in the revised Dockerfile. That's all that the kbase/minideb image gets that's not in core debian.

The sdkbase image provides things like `ca-certificates`, `wget` and so on on the system level. Making sure those are updated properly is good practice for things that, say, contact the internet at all. It does use `make`, so that's important.  It doesn't use the various compression tools directly, so I don't think they're necessary. If you're installing `dockerize` with wget, then you'll need that here.

The python layer has miniconda and various addons. IMO building a conda virtual environment inside a Docker image is overkill unless you have a clear case for it or use install tools that take advantage of it. Since it's on the older side and feeds is a relatively simple flask app, I don't think it's necessary.

biopython and numpy aren't used at all

`requests` is, and the `requests[security]` package comes with pyOpenSSL, cryptography, and idna, all of which help make more secure requests. But, that's now outdated in the most recent requests package, which includes relevant things as dependencies. Since requests is included as a requirement already, that's probably fine. It should be updated for security's sake, though, or at least kept on a short list for triage to keep this from sprawling too much further.

I don't believe `jsonrpcbase` is used by anything directly since the Python KBase API clients are all pretty much hand-made. @MrCreosote can correct me since he's eyeball deep in SDK code right now.

Honestly, that image is 6 years old, and even though the Python requirements aren't version-pinned, they're all gonna be really ancient in the image that feeds is based on.

Everything else should have been included in the requirements.txt - flask, gunicorn, etc., etc.


So, summary bullets here:
* feeds has a Makefile, so make sure `make` is installed. I don't know if that's in the base python image you're using. You should check.
* dockerize is needed, and installed with `wget`. Make sure the latest `wget` is installed.
* IMO conda environments and package management isn't necessary in this case and can be left out, as can the various python parts that get installed.
* Make a note to update relevant requirements to the latest version. I'm sure dependabot will squawk about those shortly.
* I don't know if there's a plan to add a `trivy` GHA to all the repos as part of this effort, but I'd feel a lot better if this passed a security check of some sort. I don't think this PR should block on that, though.
* Final point - copying the requirements.txt, then the entire module just duplicates that file and doesn't really save that much caching. Please change that.

2024-11-21 21:46 UTC, briehl commented on Dockerfile
> +RUN pip install -r requirements.txt
I don't see why this happens first. Shouldn't the whole module get copied at once, then just install from `/kb/module/requirements.txt`?

2024-11-21 21:54 UTC, MrCreosote commented
> jsonrpcbase

This is needed for python SDK servers. Feeds is not SDK compiled riight?

> I don't see why this happens first. Shouldn't the whole module get copied at once, then just install from /kb/module/requirements.txt?

I assume so code changes don't force a reinstall of all the pip dependencies, making repeated builds much faster

2024-11-21 22:07 UTC, briehl commented
> > I don't see why this happens first. Shouldn't the whole module get copied at once, then just install from /kb/module/requirements.txt?
> 
> I assume so code changes don't force a reinstall of all the pip dependencies, making repeated builds much faster
> 

Sure, I guess that makes sense for local hacking and building and testing. AFAIK Github doesn't do image caching, does it?

Either way, I don't feel strongly.

2024-11-21 22:17 UTC, Xiangs18 commented on Dockerfile
> +RUN pip install -r requirements.txt
By copying only the requirements.txt and installing the dependencies before copying the rest of the project, Docker will only reinstall the dependencies when requirements.txt changes, not when other files in the project change.

2024-11-21 22:20 UTC, MrCreosote commented
> AFAIK Github doesn't do image caching, does it?

I *think* there's a way to do it, but I've never tried.

2024-11-21 22:32 UTC, Xiangs18 commented
> So, @Xiangs18 , make sure that make gets installed on the image, and this is fine.

`make` already included in the base image: `python:3.9.19`

2024-11-21 22:52 UTC, Xiangs18 commented
> I don't know if there's a plan to add a trivy GHA to all the repos as part of this effort, but I'd feel a lot better if this passed a security check of some sort. I don't think this PR should block on that, though.

We do have a ticket for trivy: https://kbase-jira.atlassian.net/jira/software/projects/SECURITY/boards/87?selectedIssue=SECURITY-7


>  I don't think this PR should block on that, though.

agree

2024-11-21 23:36 UTC, briehl approved these changes

2024-11-22 00:19 UTC, merged